services:
  web:
    build: ./policykit/
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./policykit:/app
    ports:
      - "8000:8000"
    env_file: "policykit/policykit/.env"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672/
      - DATABASE_URL=postgres://user:password@postgres:5432/policykit
      - DJANGO_SECRET_KEY=supersecretkey
      - SERVER_URL=https://${SUBDOMAIN}.loca.lt
      - ALLOWED_HOSTS=web,.localhost,127.0.0.1,[::1]
    depends_on:
      - rabbit
      - postgres

  localtunnel:
    env_file: "policykit/policykit/.env"
    build: ./policykit/localtunnel/
    command: lt --port 8000 --local-host web --subdomain ${SUBDOMAIN}
    depends_on:
      - web

  celery:
    build: ./policykit/
    user: django-user
    command: "celery -A policykit worker --loglevel=info"
    volumes:
      - ./policykit:/app
    env_file: "policykit/policykit/.env"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672/
      - DATABASE_URL=postgres://user:password@postgres:5432/policykit
    depends_on:
      - rabbit
      - postgres

  celerybeat:
    build: ./policykit/
    user: django-user
    command: "celery -A policykit beat --loglevel=info"
    env_file: "policykit/policykit/.env"
    volumes:
      - ./policykit:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672/
      - DATABASE_URL=postgres://user:password@postgres:5432/policykit
    depends_on:
      - rabbit
      - postgres

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=policykit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
